title: "Welcome to Data Analytics in Business (MGT 6203)!"
theme: jekyll-theme-minimal

description: >
  By Zhaohu(Jonathan) Fan <br />
  "Data drives decisions, and analytics illuminates insights."

show_downloads: false
github:
  is_project_page: false
